# This workflow will build a golang project for MacOS
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: build for macos
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.24'

    - name: Build
      run: go build .

    - name: Artifact
      uses: actions/upload-artifact@v4
      with:
        name: pi-binary-macos
        path: pi-im
